name: Build Mihon Extension

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build extension
        run: ./gradlew :bibliozero_extension:assembleRelease --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bibliozero-extension
          path: bibliozero_extension/build/outputs/apk/release/*.apk
